spring:
  cloud:
    gateway:
      globalcors:
        cors-configuration:
          '[/**]':
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "OPTIONS"